### ISSUE TITLE
Block 1,952,187 not fully processed

### ISSUE THREAD

**Issue by brianlenz** [CityOfZion/neo-scan#120]
We noticed that one of our balances isn't displaying correctly on neoscan:

https://neoscan.io/address/AZXKdEc2M73qeQMmPj2zmKJFDWmzQf8Gyr

It's short 1 NEO. Neoscan is currently showing a balance of 361 NEO, but the actual balance is 362 (and a local neo-python node confirms this). I've tracked it down to block 1,952,187, which apparently didn't get processed fully:

https://neoscan.io/block/64f9b553f89b48305f8d4bc4879624d4abb35659830f2c4ce856fc7e4dce037b

It reports 29 transactions in the block (which is correct), but page 2 of transactions shows no results:

https://neoscan.io/block/64f9b553f89b48305f8d4bc4879624d4abb35659830f2c4ce856fc7e4dce037b/2

In particular, here's our transaction that is missing, which is throwing off the address balance:

https://neoscan.io/transaction/6eda62442a3f5ae98f6520b6118760060ec7e0a4480729e0f6c9aa59e747ae39

Note that this transaction does _not_ show up in the address' transaction list, as you'd probably expect since that transaction seems to not have been imported properly.

**Comment by brianlenz** [comment]
Note that I just transferred all of the NEO out of the address here, and the balance properly reflects zero. Interestingly, now block 1,952,187 _is_ showing the transaction that was missing (whereas it did not previously). I still don't see all 29 transactions in the block being displayed, however.

**Comment by lucianoengel** [comment]
Yes! the problem is, when the the network is down the sync job might end in the middle of a block writing process. I have a repair algorithm to deal with it. That works in the following manner: since each tx uses previous tx outputs as inputs, if it can't find a previous tx it automatically calls the nodes for the missing information and then "repair" the block. Note that for this repair to happen, there must be a new tx coming in that will require the past tx information. So any other missing information in that same block will only be repaired once the addresses in the missing tx's make a new tx.  Hope that clarifies :)
