### ISSUE TITLE
More detailed instructions to run neo scan.

### ISSUE THREAD

**Issue by j4ys0n** [CityOfZion/neo-scan#173]
Hello,

I'm finding the instructions to run the block explorer a little difficult to follow. It's not very clear on how to actually get it running. I've tried `docker-compose up -d` but that doesn't seem to do everything. It tells you to go to `/data` where there's another Dockerfile, but docker isn't installed. Am I supposed to install docker inside the container and run a container in the container? What's missing?

**Comment by adrienmo** [comment]
Hi @j4ys0n are you trying to run neo-scan for development or just to run it locally ?
Maybe the misunderstanding comes from the 2nd command:
- `docker-compose up -d`
- `docker exec -it neoscan_phoenix_1 sh`
- `cd /data`

Right now the name is not fixed so it depends on your folder name, maybe you need to run:

`docker exec -it neo-scan_phoenix_1 sh`

the rest of the commands seems correct "To start your The Application/Phoenix server" and "To run the tests". However you should change the dev and test configuration to change "localhost" to "postgres" because you are inside docker. Files to change are here:

- https://github.com/CityOfZion/neo-scan/blob/master/apps/neoscan/config/dev.exs#L9
- https://github.com/CityOfZion/neo-scan/blob/master/apps/neoscan/config/test.exs#L9

**Comment by j4ys0n** [comment]
I'm not sure why this was closed.

I'm interested in running this in production and being able to host on my own vps. The goal is to be able to use the API endpoints.

**Comment by lucianoengel** [comment]
this was closed because you didn't provide any feedback from our answer.

**Comment by j4ys0n** [comment]
please allow more time. i was sleeping.

**Comment by lucianoengel** [comment]
no problem, if you still can't run it, have any trouble or suggestions to improve the readme I'll open it again.

**Comment by j4ys0n** [comment]
i still can't run it. i'm not looking for dev, i need to run a production node and use the api.

**Comment by lucianoengel** [comment]
Well, to run you just need to execute the commands as stated in the readme. It doesn't matter what you'll be using it for.

**Comment by j4ys0n** [comment]
I tried the steps yesterday and they didn't work. Also, I don't want to use localhost as this is on a VPS. the dockerfile doesn't seem to bind port 4000 so that it can be accessed remotely.

**Comment by adrienmo** [comment]
@j4ys0n 
After verification it seems there were indeed some issue in the description, this is now fixed, you can follow those exact step to get it running:

```
git clone https://github.com/CityOfZion/neo-scan.git
cd neo-scan
docker-compose up -d
docker exec -it phoenixdev sh
cd /data
mix deps.get
mix ecto.create && mix ecto.migrate
cd apps/neoscan_web/assets && npm install
cd ../ && mix phx.server
```

you should be able to access to http://localhost:4000 a little while after

**Comment by j4ys0n** [comment]
awesome! thank you. i will try it.
