### ISSUE TITLE
The get_height API is not same behavior with API document

### ISSUE THREAD

**Issue by yongjiema** [CityOfZion/neo-scan#333]
It returns latest block index of the neoscan db from the `get_height` API document, it's possible get different data.

e.g. DB is having blocks from 0 to 1000 except 998 and 999 at a time, it is returning `1001 - 2 - 1 = 999 - 1 = 998`, but the latest block index is 1000.

Current behavior: `total count` - 1
Expected behavior: same behavior with API document

**Comment by adrienmo** [comment]
My first observation would be: this is a temporary state, it is only when neoscan is syncing that this problem will happen.

But I understand the problem, if we want to make neoscan robust for 3rd party to rely on it we might want to cover this case. In my opinion in the given case we should return the value `997` instead, because block can be safely consumed until the 997 block, if we were returning 1000 then the third party service could falsely assume it can read 998 and 999 block but they are not loaded yet. What do you think?

**Comment by yongjiema** [comment]
For my view, I would design as below:

1. Get and persist the original blocks from blockchain to DB
2. Calculate the related data in sequence base on the origin blocks, and pause until a missing block is synced

then the explorer will not have to re-sync if it has any issue, just re-calculate base on existing blocks, and return `997` to client as `1000` is not calculated yet.
