### ISSUE TITLE
get_unclaimed vs get_claimable

### ISSUE THREAD

**Issue by some-dev** [CityOfZion/neo-scan#401]
What's the diffenece between "unclaimed" property on this 2-endpoints?
For example
https://neoscan.io/api/main_net/v1/get_claimable/AVfPM78HkWPX4i1gQBfR3m9fMTxJVGK29C
returns "unclaimed" = 0 but
https://neoscan.io/api/main_net/v1/get_unclaimed/AVfPM78HkWPX4i1gQBfR3m9fMTxJVGK29C but returns "unclaimed" = 0.0001512 at the moment.
Why do get_claimable returns 0?
Is there are any timeout between transaciton claims?
Thanks in advance!

**Comment by lucianoengel** [comment]
like the api docs say (https://neoscan.io/docs/index.html#api-v1-get-5) 
get_claimable: Returns the AVAILABLE claimable transactions for an address, from its hash.

like the api docs say (https://neoscan.io/docs/index.html#api-v1-get-10)
get_unclaimed: Returns the unclaimed gas for an address from its hash.

basically get_claimable returns only the available unclaimed gas whereas get_unclaimed returns the total unclaimed, available + unavailable.

I don't understant what you mean with "timeout between transaciton claims"

**Comment by some-dev** [comment]
Thanks for the answer - could you clarify - what does "unavailable" gas means?
Why it is unavailable?

**Comment by lucianoengel** [comment]
because it's not yet spent, so you can't yet claim it

according to: https://docs.neo.org/en-us/faq.html

What is GAS？How to acquire GAS？

GAS represents the right to use the Neo Blockchain. NEO network charges GAS for the new assets issuance as well as for smart contract running and storage. In the genesis block GAS is 0 and it is generated as new blocks generate. Once NEO is acquired, GAS is generated in the system following the algorithms. GAS has two status, available and unavailable. Once NEO is spent (i.e. transferred out) from the account, the relevant GAS turns to available. NEO holders can initiate a claim transaction at any time to claim available GAS to the NEO address.

**Comment by some-dev** [comment]
Got it thanks a lot
