### ISSUE TITLE
get_claimable on Multisig account doesn't returns any claims

### ISSUE THREAD

**Issue by chrismcna** [CityOfZion/neo-scan#429]
Hi,
I've created a multi sig address using neon-js and I'm expecting claimable gas but get_claimable api doesnt return any claims

http://api.neoscan.io/api/main_net/v1/get_claimable/APKaDaTu65uNDNyMRmxkA9qofU5DJxTgUy 
https://neoscan.io/address/APKaDaTu65uNDNyMRmxkA9qofU5DJxTgUy
![get_claimable ](https://user-images.githubusercontent.com/15839356/65372102-9ae3bc80-dc63-11e9-8877-c27b5380b1b6.png)

**Comment by adrienmo** [comment]
Hi,

You are not using the right endpoint, you should use:

https://api.neoscan.io/api/main_net/v1/get_unclaimed/APKaDaTu65uNDNyMRmxkA9qofU5DJxTgUy

instead.

`get_claimable` only list what you can directly claim (basically neo that went into your account and then spent).

`get_unclaimed` is giving you an estimation on how much gas you could claim if you were spending  your neo at the current block. (Of course you can transfer them to your own address to `spend` them). That's why claiming gas on neo blockchain is always implemented in two steps in wallets, first send neo to yourself, then claim gas.

**Comment by chrismcna** [comment]
Thank you,
You have cleared up my miss understanding.
I have sent my neo to myself and i get claims returned, which i have now claimed.

I was using the guide http://cityofzion.io/neon-js/docs/en/guides/basic/claimgas.html
the note state "This does not automatically send your NEO to yourself" but I didn't realise the importance of this note  and how it affects my code.

Thanks again for all your hard work.
