### ISSUE TITLE
Error after starting the app second time

### ISSUE THREAD

**Issue by vladucu** [CityOfZion/neo-scan#44]
Once I pulled the app and then restarted....started seeing this constraint error 

<img width="1674" alt="screen shot 2017-10-11 at 01 12 43" src="https://user-images.githubusercontent.com/160955/31413387-9d34030e-ae21-11e7-8be9-a0b23cd71bea.png">

Can you confirm this is an issue or is it just me doing something crazy?

**Comment by steffenix** [comment]
I have the same issue.

**Comment by lucianoengel** [comment]
This is known behavior, the block queries in blocks.ex need to be adjusted. In production they are set to look for blocks higher than 1300000 to speed up. Since you don't have that many blocks yet, the query return 0 and it tries to re-add block 0, leading to a constraint error. Just change the queries to where: b.index > -1, instead of 1300000

**Comment by vladucu** [comment]
PS: Might be useful to mention this for new up-comers...maybe Readme?

**Comment by lucianoengel** [comment]
No need. The new branch has -1 as default already. I'm only changing that in the server machine
